export const PERMISSIONS = {
  // Administration
  READ_LOGO_MANAGEMENT: 1,
  WRITE_LOGO_MANAGEMENT: 2,

  READ_BANNER_MANAGEMENT: 3,
  WRITE_BANNER_MANAGEMENT: 4,

  READ_LERG_MANAGEMENT: 5,
  WRITE_LERG_MANAGEMENT: 6,

  READ_CDR_SERVER_MANAGEMENT: 7,
  WRITE_CDR_SERVER_MANAGEMENT: 8,

  READ_LRN_MANAGEMENT: 9,
  WRITE_LRN_MANAGEMENT: 10,

  PRODUCT_TYPE_MANAGEMENT: 11,
  PRODUCT_MANAGEMENT: 12,

  EMAIL_CONFIGURATION: 13,

  BILLING_ADDRESS: 14,
  VENDOR_INVOICES: 15,

  // Customer Management
  READ_CUSTOMERS: 16,
  WRITE_CUSTOMERS: 17,

  READ_ROLES: 18,
  WRITE_ROLES: 19,

  READ_USERS: 20,
  WRITE_USERS: 21,

  // Vendor Management
  READ_VENDORS: 22,
  WRITE_VENDORS: 23,

  READ_VENDOR_RATES: 24,
  WRITE_VENDOR_RATES: 25,

  VENDOR_COMPARATION: 26,

  // Number Management
  READ_BUY_NUMBERS: 27,
  WRITE_BUY_NUMBERS: 28,

  READ_CUSTOMER_NUMBERS: 29,
  WRITE_CUSTOMER_NUMBERS: 30,

  READ_TFN_NUMBERS: 31,
  WRITE_TFN_NUMBERS: 32,

  READ_DID_NUMBERS: 33,
  WRITE_DID_NUMBERS: 34,

  // Billing Management
  CREATE_BILLING_INVOICE: 35,
  CREATE_BILLING_STATEMENT: 36,
  VIEW_BILLING_STATEMENT: 37,
  TAX_MANAGEMENT: 38,
  RERATE_CALLS: 39,
  CUSTOMER_PAYMENT: 40,
  STATEMENT_ACCOUNT: 41,

  // Reports
  CDR_LOG: 42,
  CDR_IMPORT_HISTORY: 43,
  LRN_Request: 44,
  VENDOR_CDRS_REPORT: 45,
  LRN_LOG: 46,
  MISSED_NAP: 47,
  READ_BALANCE: 48,
  VIEW_BILLING_INVOICE: 49,

  READ_CUSTOMER_RATES: 50,
  WRITE_CUSTOMER_RATES: 51,

  READ_CUSTOMER_PRODUCTS: 52,
  WRITE_CUSTOMER_PRODUCTS: 53,

  READ_CUSTOMER_TAX: 54,
  WRITE_CUSTOMER_TAX: 55,

  READ_CUSTOMER_DOCUMENT: 56,
  WRITE_CUSTOMER_DOCUMENT: 57,
};
